;;; nameframe-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from nameframe.el

(autoload 'nameframe-switch-frame "nameframe" "\
Interactively switch to an existing frame with name FRAME-NAME.

(fn FRAME-NAME)" t)
(autoload 'nameframe-create-frame "nameframe" "\
Interactively create a frame with name FRAME-NAME and switch to it.

(fn FRAME-NAME)" t)
(register-definition-prefixes "nameframe" '("nameframe-"))

;;; End of scraped data

(provide 'nameframe-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; nameframe-autoloads.el ends here
