;;; shelldon-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from shelldon.el

(autoload 'shelldon "shelldon" "\
Execute given asynchronously in the minibuffer with output history.

If the user tries to change the workdir while the command is executing, catch
the change and re-execute in the new context." t)
(autoload 'shelldon-loop "shelldon" "\
Loops the shelldon command to more closely emulate a terminal." t)
(autoload 'shelldon-output-history "shelldon" "\
Displays the output of the selected command from the shelldon history." t)
(autoload 'shelldon-send-line-at-point "shelldon" "\
Send the current line to shelldon and display the result." t)
(autoload 'shelldon-send-region "shelldon" "\
Send region from START to END to shelldon and display the result.

(fn START END)" t)
(register-definition-prefixes "shelldon" '("shelldon-"))

;;; End of scraped data

(provide 'shelldon-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; shelldon-autoloads.el ends here
