;;; register-quicknav-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from register-quicknav.el

(defvar register-quicknav-buffer-only nil "\
Cycle only through position registers in current buffer.")
(custom-autoload 'register-quicknav-buffer-only "register-quicknav" t)
(put 'register-quicknav-buffer-only 'safe-local-variable #'booleanp)
(autoload 'register-quicknav-next-register "register-quicknav" "\
Jump to next position register." t)
(autoload 'register-quicknav-prev-register "register-quicknav" "\
Jump to previous position register." t)
(autoload 'register-quicknav-clear-current-register "register-quicknav" "\
Clear last jumped-to position register from `register-alist'.
Deletes the value of `register-quicknav--last-register' from `register-alist'." t)
(autoload 'register-quicknav-point-to-unused-register "register-quicknav" "\
Store current location of point in next unused register.
Searches the range between
`register-quicknav-unused-registers-begin' and
`register-quicknav-unused-registers-end'." t)
(autoload 'register-quicknav-clear-unused-registers-range "register-quicknav" "\
Clear all registers in the range used by `register-quicknav-point-to-unused-register'." t)
(register-definition-prefixes "register-quicknav" '("register-quicknav-"))

;;; End of scraped data

(provide 'register-quicknav-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; register-quicknav-autoloads.el ends here
