;;; company-ansible-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from company-ansible.el

(autoload 'company-ansible "company-ansible"
"Company backend for ansible yaml files.

(fn COMMAND &optional ARG &rest IGNORED)" t)


;;; Generated autoloads from company-ansible-keywords.el

(register-definition-prefixes "company-ansible-keywords" '("company-ansible-keywords"))

;;; End of scraped data

(provide 'company-ansible-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; company-ansible-autoloads.el ends here
