;;; flycheck-yamllint-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flycheck-yamllint.el

(autoload 'flycheck-yamllint-setup "flycheck-yamllint"
"Setup Flycheck YAMLLint integration." t)

;;; End of scraped data

(provide 'flycheck-yamllint-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flycheck-yamllint-autoloads.el ends here
