;;; ix-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ix.el

(autoload 'ix-delete "ix"
"Delete a post, this requires you to be logged in. Specify the
   post id or the url

(fn IX-URL)" t)
(autoload 'ix "ix"
"Paste the region at http://ix.io, url returned is saved to the
   kill ring. It is recommended to set up a username and token by
   configuring the variables `ix-user' and `ix-token'

(fn START END)" t)
(autoload 'ix-browse "ix"
"Browse a paste from http://ix.io, given an input of either a
   post identifier or the complete url. The output is displayed in a
   special buffer, *ix*. If the buffer needs to be saved for some reason
   it has to be done manually

(fn IX-URL)" t)
(register-definition-prefixes "ix" '("ix-"))

;;; End of scraped data

(provide 'ix-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ix-autoloads.el ends here
