;;; webpaste-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from webpaste.el

(let ((loads (get 'webpaste 'custom-loads))) (if (member '"webpaste" loads) nil (put 'webpaste 'custom-loads (cons '"webpaste" loads)) (put 'web 'custom-loads (cons 'webpaste (get 'web 'custom-loads)))))
(autoload 'webpaste-paste-region "webpaste"
"Paste selected region to some paste service.
Argument POINT Current point.
Argument MARK Current mark.

(fn POINT MARK)" t)
(autoload 'webpaste-paste-buffer "webpaste"
"Paste current buffer to some paste service." t)
(autoload 'webpaste-paste-buffer-or-region "webpaste"
"Paste current buffer or selected region to some paste service.
Takes optional POINT and MARK to paste a region.

(fn &optional POINT MARK)" t)
(register-definition-prefixes "webpaste" '("webpaste-"))

;;; End of scraped data

(provide 'webpaste-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; webpaste-autoloads.el ends here
