;;; rego-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from rego-mode.el

(add-to-list 'auto-mode-alist '("\\.rego\\'" . rego-mode))
(autoload 'rego-mode "rego-mode"
"Major mode for editing Rego files.

In addition to any hooks its parent mode `prog-mode' might have run, this mode
runs the hook `rego-mode-hook', as the final or penultimate step during
initialization.

\\{rego-mode-map}" t)
(register-definition-prefixes "rego-mode" '("rego-"))

;;; End of scraped data

(provide 'rego-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; rego-mode-autoloads.el ends here
