;;; bookmark-in-project-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from bookmark-in-project.el

(autoload 'bookmark-in-project-jump-next "bookmark-in-project"
"Jump to the next bookmark." t)
(function-put 'bookmark-in-project-jump-next 'important-return-value 'nil)
(autoload 'bookmark-in-project-jump-previous "bookmark-in-project"
"Jump to the previous bookmark." t)
(function-put 'bookmark-in-project-jump-previous 'important-return-value 'nil)
(autoload 'bookmark-in-project-jump "bookmark-in-project"
"Jump to a bookmark in the current project." t)
(function-put 'bookmark-in-project-jump 'important-return-value 'nil)
(autoload 'bookmark-in-project-jump-other-window "bookmark-in-project"
"Jump to a bookmark in another window, see `bookmark-in-project-jump'." t)
(function-put 'bookmark-in-project-jump-other-window 'important-return-value 'nil)
(autoload 'bookmark-in-project-jump-other-frame "bookmark-in-project"
"Jump to a bookmark in another frame, see `bookmark-in-project-jump'." t)
(function-put 'bookmark-in-project-jump-other-frame 'important-return-value 'nil)
(autoload 'bookmark-in-project-toggle "bookmark-in-project"
"Create or delete a bookmark on the current line." t)
(function-put 'bookmark-in-project-toggle 'important-return-value 'nil)
(autoload 'bookmark-in-project-delete-all "bookmark-in-project"
"Delete all bookmarks in the project.
If optional argument NO-CONFIRM is non-nil, don't ask for
confirmation.

(fn &optional NO-CONFIRM)" t)
(function-put 'bookmark-in-project-delete-all 'important-return-value 'nil)
(register-definition-prefixes "bookmark-in-project" '("bookmark-in-project-"))

;;; End of scraped data

(provide 'bookmark-in-project-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; bookmark-in-project-autoloads.el ends here
