;;; consult-todo-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from consult-todo.el

(autoload 'consult-todo "consult-todo" "\
Jump to hl-todo keywords in BUFFERS.
If BUFFERS is nil, use current buffer instead.

(fn &optional BUFFERS)" t)
(autoload 'consult-todo-all "consult-todo" "\
Jump to hl-todo keywords in all `hl-todo-mode' enabled buffers." t)
(autoload 'consult-todo-clear-cache "consult-todo" "\
Clear cache stored in `consult-todo--cache'.
If arg ALL is non-nil, clear all cache.

(fn &optional ALL)" t)
(autoload 'consult-todo-dir "consult-todo" "\
Jump to hl-todo keywords in files located in DIRECTORY.
If optional arg DIRECTORY is nil, rgrep in default directory. With
\\[universal-argument] enable, select DIRECTORY instead.

(fn &optional DIRECTORY)" t)
(autoload 'consult-todo-project "consult-todo" "\
Jump to hl-todo keywords in current project." t)
(register-definition-prefixes "consult-todo" '("consult-todo-"))

;;; End of scraped data

(provide 'consult-todo-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; consult-todo-autoloads.el ends here
