;;; phi-rectangle-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from phi-rectangle.el

(defvar phi-rectangle-mode nil "\
Non-nil if Phi-Rectangle mode is enabled.
See the `phi-rectangle-mode' command
for a description of this minor mode.")
(custom-autoload 'phi-rectangle-mode "phi-rectangle" nil)
(autoload 'phi-rectangle-mode "phi-rectangle" "\
minor mode to set rectangle-mark

This is a global minor mode.  If called interactively, toggle the
`Phi-Rectangle mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='phi-rectangle-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "phi-rectangle" '("kill-new" "phi-rectangle-"))

;;; End of scraped data

(provide 'phi-rectangle-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; phi-rectangle-autoloads.el ends here
