;;; quelpa-leaf-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from quelpa-leaf.el

(autoload 'quelpa-leaf-init "quelpa-leaf"
"Add additional keywords to `leaf'.
If RENEW is non-nil, renew leaf-{keywords, normalize} cache.

(fn &optional RENEW)")
(register-definition-prefixes "quelpa-leaf" '("quelpa-leaf-"))

;;; End of scraped data

(provide 'quelpa-leaf-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; quelpa-leaf-autoloads.el ends here
