;;; jenkinsfile-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from jenkinsfile-mode.el

(autoload 'jenkinsfile-mode "jenkinsfile-mode"
"Major mode for editing Jenkins declarative pipeline files.

In addition to any hooks its parent mode `groovy-mode' might have run, this mode
runs the hook `jenkinsfile-mode-hook', as the final or penultimate step during
initialization.

\\{jenkinsfile-mode-map}" t)
(add-to-list 'auto-mode-alist '("Jenkinsfile\\'" . jenkinsfile-mode))
(register-definition-prefixes "jenkinsfile-mode" '("jenkinsfile-mode-"))

;;; End of scraped data

(provide 'jenkinsfile-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; jenkinsfile-mode-autoloads.el ends here
