;;; spatial-navigate-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from spatial-navigate.el

(autoload 'spatial-navigate-forward-vertical-box "spatial-navigate"
"Jump forward vertically ARG times across blank-space and non-blank-space.
A negative ARG reverses the motion.
Return the number of steps remaining (0 when all succeed)
or nil when the motion could not be performed.

Use for a box cursor.

(fn ARG)" t)
(function-put 'spatial-navigate-forward-vertical-box 'important-return-value 'nil)
(autoload 'spatial-navigate-backward-vertical-box "spatial-navigate"
"Jump backward vertically ARG times across blank-space and non-blank-space.
A negative ARG reverses the motion.
Return the number of steps remaining (0 when all succeed)
or nil when the motion could not be performed.

Use for a box cursor.

(fn ARG)" t)
(function-put 'spatial-navigate-backward-vertical-box 'important-return-value 'nil)
(autoload 'spatial-navigate-forward-vertical-bar "spatial-navigate"
"Jump forward vertically ARG times across blank-space and non-blank-space.
A negative ARG reverses the motion.
Return the number of steps remaining (0 when all succeed)
or nil when the motion could not be performed.

Use for a bar cursor.

(fn ARG)" t)
(function-put 'spatial-navigate-forward-vertical-bar 'important-return-value 'nil)
(autoload 'spatial-navigate-backward-vertical-bar "spatial-navigate"
"Jump backward vertically ARG times across blank-space and non-blank-space.
A negative ARG reverses the motion.
Return the number of steps remaining (0 when all succeed)
or nil when the motion could not be performed.

Use for a bar cursor.

(fn ARG)" t)
(function-put 'spatial-navigate-backward-vertical-bar 'important-return-value 'nil)
(autoload 'spatial-navigate-forward-horizontal-box "spatial-navigate"
"Jump forward horizontally ARG times across blank-space and non-blank-space.
A negative ARG reverses the motion.
Return the number of steps remaining (0 when all succeed)
or nil when the motion could not be performed.

Use for a box cursor.

(fn ARG)" t)
(function-put 'spatial-navigate-forward-horizontal-box 'important-return-value 'nil)
(autoload 'spatial-navigate-backward-horizontal-box "spatial-navigate"
"Jump backward horizontally ARG times across blank-space and non-blank-space.
A negative ARG reverses the motion.
Return the number of steps remaining (0 when all succeed)
or nil when the motion could not be performed.

Use for a box cursor.

(fn ARG)" t)
(function-put 'spatial-navigate-backward-horizontal-box 'important-return-value 'nil)
(autoload 'spatial-navigate-forward-horizontal-bar "spatial-navigate"
"Jump forward horizontally ARG times across blank-space and non-blank-space.
A negative ARG reverses the motion.
Return the number of steps remaining (0 when all succeed)
or nil when the motion could not be performed.

Use for a bar cursor.

(fn ARG)" t)
(function-put 'spatial-navigate-forward-horizontal-bar 'important-return-value 'nil)
(autoload 'spatial-navigate-backward-horizontal-bar "spatial-navigate"
"Jump backward horizontally ARG times across blank-space and non-blank-space.
A negative ARG reverses the motion.
Return the number of steps remaining (0 when all succeed)
or nil when the motion could not be performed.

Use for a bar cursor.

(fn ARG)" t)
(function-put 'spatial-navigate-backward-horizontal-bar 'important-return-value 'nil)
(register-definition-prefixes "spatial-navigate" '("spatial-navigate-"))

;;; End of scraped data

(provide 'spatial-navigate-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; spatial-navigate-autoloads.el ends here
