;;; goto-char-preview-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from goto-char-preview.el

(autoload 'goto-char-preview "goto-char-preview"
"Preview goto char." t)
(autoload 'goto-char-preview-relative "goto-char-preview"
"Preview goto char relative." t)
(register-definition-prefixes "goto-char-preview" '("goto-char-preview-"))

;;; End of scraped data

(provide 'goto-char-preview-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; goto-char-preview-autoloads.el ends here
