;;; smart-hungry-delete-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from smart-hungry-delete.el

(autoload 'smart-hungry-delete-add-default-hooks "smart-hungry-delete" "\
Add to some hooks for sensible default character/word/delimiter configuration." t)
(autoload 'smart-hungry-delete-backward-char "smart-hungry-delete" "\
If there is more than one char of whitespace between previous word and point,
delete all but one unless there's whitespace or newline directly
after the point--which will delete all whitespace back to
word--, else fall back to (delete-backward-char 1).

With prefix argument ARG, just delete a single char.

(fn ARG)" t)
(autoload 'smart-hungry-delete-forward-char "smart-hungry-delete" "\
If there is more than one char of whitespace between point and next word,
delete all but one unless there's whitespace or newline directly
before the point--which will delete all whitespace up to word--,
else fall back to (delete-char 1).

With prefix argument ARG, just delete a single char.

(fn ARG)" t)
(register-definition-prefixes "smart-hungry-delete" '("smart-hungry-delete-"))

;;; End of scraped data

(provide 'smart-hungry-delete-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; smart-hungry-delete-autoloads.el ends here
