;;; mode-line-idle-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from mode-line-idle.el

(autoload 'mode-line-idle "mode-line-idle"
"Delayed evaluation of CONTENT, delayed by DELAY-IN-SECONDS.

CONTENT should be a mode-line construct (e.g., a symbol or `:eval' form).
DEFAULT-TEXT is displayed until the idle timer fires and CONTENT is evaluated.

Argument KEYWORDS is a property list of optional keywords:

- `:interrupt' When non-nil, interrupt evaluation on keyboard input
  (use for long running actions).
- `:literal' When non-nil, replace `%' with `%%',
  to prevent `mode-line-format' from formatting these characters.

(fn DELAY-IN-SECONDS CONTENT DEFAULT-TEXT &rest KEYWORDS)")
(function-put 'mode-line-idle 'important-return-value 't)
(autoload 'mode-line-idle-force-update "mode-line-idle"
"Calculate pending `mode-line-idle' entries immediately.
When DELAY-IN-SECONDS is nil, all pending values are calculated,
otherwise ignore pending timers over this time.
Return non-nil when the mode-line was updated.

(fn &optional DELAY-IN-SECONDS)")
(function-put 'mode-line-idle-force-update 'important-return-value 't)
(register-definition-prefixes "mode-line-idle" '("mode-line-idle--"))

;;; End of scraped data

(provide 'mode-line-idle-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; mode-line-idle-autoloads.el ends here
