;;; popup-imenu-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from popup-imenu.el

(autoload 'popup-imenu "popup-imenu"
"Open the popup window with imenu items." t)
(register-definition-prefixes "popup-imenu" '("popup-imenu-"))

;;; End of scraped data

(provide 'popup-imenu-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; popup-imenu-autoloads.el ends here
