;;; isearch-project-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from isearch-project.el

(autoload 'isearch-project-forward-symbol-at-point "isearch-project"
"Incremental search symbol forward at current point in the project." t)
(autoload 'isearch-project-forward-thing-at-point "isearch-project"
"Incremental search thing forward at current point in the project." t)
(autoload 'isearch-project-forward "isearch-project"
"Incremental search forward in the project." t)
(register-definition-prefixes "isearch-project" '("isearch-project-"))

;;; End of scraped data

(provide 'isearch-project-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; isearch-project-autoloads.el ends here
