;;; ace-jump-zap-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ace-jump-zap.el

(autoload 'ace-jump-zap-up-to-char "ace-jump-zap" "\
Call `ace-jump-char-mode' and zap all characters up to the selected character." t)
(autoload 'ace-jump-zap-to-char "ace-jump-zap" "\
Call `ace-jump-char-mode' and zap all characters up to and including the selected character." t)
(autoload 'ace-jump-zap-to-char-dwim "ace-jump-zap" "\
Without PREFIX, call `zap-to-char'.
With PREFIX, call `ace-jump-zap-to-char'.

(fn &optional PREFIX)" t)
(autoload 'ace-jump-zap-up-to-char-dwim "ace-jump-zap" "\
Without PREFIX, call `zap-up-to-char'.
With PREFIX, call `ace-jump-zap-up-to-char'.

(fn &optional PREFIX)" t)
(register-definition-prefixes "ace-jump-zap" '("ajz/"))

;;; End of scraped data

(provide 'ace-jump-zap-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ace-jump-zap-autoloads.el ends here
