;;; alsamixer-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from alsamixer.el

(autoload 'alsamixer-set-volume "alsamixer" "\
Set volume to PERC.

(fn PERC)" t)
(autoload 'alsamixer-up-volume "alsamixer" "\
Set volume, step size can be passed by PERC.

(fn &optional PERC)" t)
(autoload 'alsamixer-down-volume "alsamixer" "\
Set volume, step size can be passed by PERC.

(fn &optional PERC)" t)
(autoload 'alsamixer-toggle-mute "alsamixer" "\
Mute / unmute." t)
(register-definition-prefixes "alsamixer" '("alsamixer-"))

;;; End of scraped data

(provide 'alsamixer-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; alsamixer-autoloads.el ends here
