;;; easy-kill-extras-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from easy-dup.el

(autoload 'easy-dup "easy-dup"
"Insert a copy of the current selection after it, or before it if BEFORE.
When not in easy-kill/easy-mark, enter `easy-mark' mode using the active
region if available, or using `easy-dup-try-things' to select something
to duplicate.  When in `rectangle-mark-mode', duplicate the rectangle
region and keep the mode active without entering `easy-mark'.

N specifies the number of copies to insert.

(fn &optional N BEFORE)" t)
(defalias 'easy-dup-after #'easy-dup)
(autoload 'easy-dup-before "easy-dup"
"Insert a copy of the current selection before it.
When not in easy-kill/easy-mark, enter `easy-mark' mode using the active
region if available, or using `easy-dup-try-things' to select something
to duplicate.  When in `rectangle-mark-mode', duplicate the rectangle
region and keep the mode active without entering `easy-mark'.

N specifies the number of copies to insert.

(fn &optional N)" t)
(register-definition-prefixes "easy-dup" '("easy-dup-try-things"))


;;; Generated autoloads from easy-kill-aj.el

(defvar easy-kill-ace-jump-enable-p t
"If non-nil, ace-jump commands can be used in easy-kill/easy-mark mode for selection.")
(custom-autoload 'easy-kill-ace-jump-enable-p "easy-kill-aj" t)
(register-definition-prefixes "easy-kill-aj" '("easy-kill-aj--"))


;;; Generated autoloads from easy-kill-buffer.el

(autoload 'easy-kill-on-buffer "easy-kill-buffer"
"Provide an easy-kill target `buffer' which selects the whole buffer.

(fn N)")
(autoload 'easy-kill-on-buffer-after-point "easy-kill-buffer"
"Provide an easy-kill target `buffer-after-point', which works like vi's `G' command.
The +/- operation determines inclusion/exclusion of the current line.

(fn N)")
(autoload 'easy-kill-on-buffer-before-point "easy-kill-buffer"
"Provide an easy-kill target `buffer-before-point', which works like vi's `gg' command.
The +/- operation determines inclusion/exclusion of the current line.

(fn N)")


;;; Generated autoloads from easy-kill-er.el

(autoload 'easy-kill-er-expand "easy-kill-er"
"Expand current candidate using the algorithms used by `expand-region'.

This applies the `er/expand-region' effect to the current
candidate ARG times.

(fn ARG)" t)
(autoload 'easy-kill-er-unexpand "easy-kill-er"
"Undo `easy-kill-er-expand'.

This applies the `er/contract-region' effect to the
current candidate ARG times.

(fn ARG)" t)
(with-eval-after-load 'multiple-cursors (add-to-list 'mc--default-cmds-to-run-for-all 'easy-kill-er-expand) (add-to-list 'mc--default-cmds-to-run-for-all 'easy-kill-er-unexpand) (add-to-list 'mc/cursor-specific-vars 'easy-kill-er-history))
(register-definition-prefixes "easy-kill-er" '("easy-kill-er-history"))


;;; Generated autoloads from easy-kill-extras.el

(let ((loads (get 'easy-kill-extras 'custom-loads))) (if (member '"easy-kill-extras" loads) nil (put 'easy-kill-extras 'custom-loads (cons '"easy-kill-extras" loads)) (put 'killing 'custom-loads (cons 'easy-kill-extras (get 'killing 'custom-loads)))))
(autoload 'easy-mark-word "easy-kill-extras"
"Start easy-mark with a word selected.

(fn N)" t)
(autoload 'easy-mark-sexp "easy-kill-extras"
"Start easy-mark with a sexp selected.

(fn N)" t)
(eval-after-load 'ace-jump-mode #'(require 'easy-kill-aj))
(eval-after-load 'multiple-cursors #'(require 'easy-kill-mc))


;;; Generated autoloads from easy-kill-line-edge.el

(autoload 'forward-line-edge "easy-kill-line-edge"
"Move between line edges.  ARG specifies which edge to move to.

If ARG is -2 or less, move to the BOL.

If ARG is -1, move to the first non-whitespace character after
the point on the line, or BOL if there is none.

If ARG is 0, stay.

If ARG is 1, move to the position right after the last
non-whitespace character after the point on the line, or EOL if
there is none.

If ARG is 2 or greater, move to the EOL.

(fn ARG)" t)
(autoload 'backward-line-edge "easy-kill-line-edge"
"Equivalent to `forward-line-edge' with a negative ARG.

(fn ARG)" t)
(autoload 'easy-kill-on-forward-line-edge "easy-kill-line-edge"
"Provide an easy-kill target `forward-line-edge', which works like vi's `^'/`0' commands in the opposite direction.

(fn N)")
(autoload 'easy-kill-on-backward-line-edge "easy-kill-line-edge"
"Provide an easy-kill target `backward-line-edge', which works like vi's `^'/`0' commands.

(fn N)")


;;; Generated autoloads from easy-kill-mc.el

(register-definition-prefixes "easy-kill-mc" '("easy-" "mc/execute-this-command-for-all-cursors--ad-easy-kill-mc"))


;;; Generated autoloads from easy-kill-to-char.el

(autoload 'easy-mark-to-char "easy-kill-to-char"
"Start easy-mark with string-to-char-forward.

(fn N)" t)
(autoload 'easy-mark-up-to-char "easy-kill-to-char"
"Start easy-mark with string-up-to-char-forward.

(fn N)" t)
 (autoload 'easy-kill-on-string-to-char-forward "easy-kill-extras")
 (autoload 'easy-kill-on-string-to-char-backward "easy-kill-extras")
 (autoload 'easy-kill-on-string-up-to-char-forward "easy-kill-extras")
 (autoload 'easy-kill-on-string-up-to-char-backward "easy-kill-extras")
(register-definition-prefixes "easy-kill-to-char" '("easy-kill-defun-string-to-char"))


;;; Generated autoloads from extra-things.el

(register-definition-prefixes "extra-things" '("angles" "beginning-op-WORD" "bquoted-string" "brackets" "curlies" "define-" "dquoted-string" "end-op-WORD" "extra-things--" "pair-thing-limit" "parentheses" "quoted-string" "squoted-string"))

;;; End of scraped data

(provide 'easy-kill-extras-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; easy-kill-extras-autoloads.el ends here
