;;; frog-jump-buffer-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from frog-jump-buffer.el

(autoload 'frog-jump-buffer "frog-jump-buffer"
"Present a `frog-menu' for jumping to an open buffer.
If FILTER-FUNCTION is present, filter the `buffer-list' with it." t)
(autoload 'frog-jump-buffer-other-window "frog-jump-buffer"
"Launch `frog-jump-buffer' with `other-window' being the default target window." t)
(register-definition-prefixes "frog-jump-buffer" '("frog-jump-buffer-"))

;;; End of scraped data

(provide 'frog-jump-buffer-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; frog-jump-buffer-autoloads.el ends here
