name: Build and push Docker Emacs image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: Docker
    steps:

    - name: Checkout code
      uses: actions/checkout@v6

    - name: set up QEMU
      uses: docker/setup-qemu-action@v4

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v7
      with:
        platforms: |
          linux/amd64
        context: .
        push: true
        tags: ${{ vars.DOCKER_USERNAME }}/emacs:latest

    # sign
    - name: Install Cosign
      uses: sigstore/cosign-installer@v4.1.0
    - name: Sign image with cosign
      env:
        COSIGN_KEY_BASE64: ${{ secrets.COSIGN_KEY_B64 }}
      run: |
        echo "$COSIGN_KEY_BASE64" | base64 -d > cosign.key && cosign sign --key cosign.key --yes serbandobrau/emacs:latest
